#!/bin/sh
# To call this script:
# curl https://raw.github.com/xseignard/use-phantomjs/master/use-phantomjs | sh
# or with a specific version
# PHANTOMJS_VERSION=1.8.2;curl https://raw.github.com/xseignard/use-phantomjs/master/use-phantomjs | sh
if [[ -z $PHANTOMJS_VERSION ]]; then
   PHANTOMJS_VERSION=1.8.2
   echo "No version provided for phantomjs, will use the last one: $PHANTOMJS_VERSION" 1>&2
fi

set -e

mkdir -p /scratch/jenkins/phantomjs
ARCH=`uname -m`

phantomjs_name=phantomjs-$PHANTOMJS_VERSION-linux-${ARCH}

test -f /scratch/jenkins/phantomjs/${phantomjs_name}.tar.bz2 ||  wget -q -P /scratch/jenkins/phantomjs https://phantomjs.googlecode.com/files/${phantomjs_name}.tar.bz2
test -f /scratch/jenkins/phantomjs/${phantomjs_name}/bin/phantomjs || tar xjf /scratch/jenkins/phantomjs/${phantomjs_name}.tar.bz2  -C /scratch/jenkins/phantomjs
export PATH=/scratch/jenkins/phantomjs/${phantomjs_name}/bin:$PATH